title:            Radically Open
tagline:          Radically Open; Training, supervision, and support for patients, carers, and health professionals.
description:      Training, supervision and support for patients, carers, and health professionals. We specialise in intensive training and online support for professionals who want to develop Radically Open DBT services, or enhance their existing practice for patients with emotional over-control.

# url: http://www.radicallyopen.net

gems:
  - jekyll-redirect-from

collections:
  events:
    output: true
    title: Events


emails:
  enquiries: erica@radicallyopen.net
  technical: roelie@radicallyopen.net

# Owner/author information
owner:
  name:           Ben Whalley
  twitter:        radicallyopen
  disqus:         None
  location: Winchester, UK
  google_analytics:
    key: "UA-51230909-1"
    domain: "radicallyopen.net"


bookings:
  email:          erica@radicallyopen.net


# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Patients & Carers
    url: /patientscarers/
  - title: Professionals
    url: /professionals/
  - title: Events
    url: /events/
  - title: Contact
    url: /contact/
  - title: Online Support Website
    url: /onlinesupport/
  

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]


intensive_generic_description: Our intensive training is a two-part fast-track programme, consisting of 2 x 5-day workshops. After completing the intensive training, practitioners may choose to progress to advanced level training and supervision.

introduction_generic_description: This workshop is a comprehensive introduction to RO DBT. It is suitable for all professionals working in the field of mental health and contributes 6 hours of Continuing Professional Development.

ce_credits_text: "- **CE credits are available for this course**"

forbooking: For additional information about booking, please email [Erica Smith](mailto:erica@radicallyopen.net) or call Roelie Hempel via +44 (0)7542 027245.

forpayments: "[Paying for courses](/payments/)"

intensive_prices_US: |
  Prices are for the complete 10 day intensive workshop (2 x 5 days).

  - Base price $4000
  - With earlybird discount (45 days before event): $3100
  - 10% discount per person for group booking (min 6)

intensive_prices_UK: |
  Prices are for the complete 10 day intensive workshop (2 x 5 days).

  - Base price £2750
  - With earlybird discount (45 days before event): £2000
  - 10% discount per-person for groups of 6 or more


introduction_prices_UK: |
  - Earlybird (30 days before event): £120 plus VAT
  - Otherwise £135 plus VAT


